# Site settings
title: 青青河边草 
email: echowuhao@gmail.com
description: "record of life"
baseurl: ""
url: "http://blog.meihao.us"
username: swuecho

paginate: 10
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
permalink: date 
highlighter: pygments

kramdown:
  input: GFM
